apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GetAppointments
  description: Gets Appointments
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: FAMS
  system: CallSchedule
  consumesApis: ['component:vhtplatform']
