apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TIBCO
  description: Will make calls to services in the CallSchedule system.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: FAMS
  system: CallSchedule
  consumesApis: ['component:GetAppointments', 'component:GetAvailableSlots', 'component:EstimateWaitTime']
