apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user
  description: User Object
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: shopping
  consumesApis: ['component:role', 'component:address', 'component:invoice']
